"""
This is a setup.py script generated by py2applet
y
Usage:
    python setup.py py2app
"""

#rm -rf build dist
#python3.8 setup.py py2app -A
#./dist/twitter_tool.app/Contents/MacOS/twitter_tool

from setuptools import setup

APP = ['twitter_tool.py']
DATA_FILES = [('', ['images', 'roberta', 'data_files'])]
OPTIONS = {"packages" : ["twint", "tensorflow.core.platform", "huggingface_hub.repository", 'certifi']}

setup(
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    py_modules = ['handler_folder', 'handler_tweet', 
    "tweet_analysis", "tweet_fetcher_twint", "tweet_filter"],
    setup_requires = ['py2app'],
)
